name: remy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-326.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  timelines:
#  url_launcher: ^6.1.0
#  firebase
#  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^16.1.0
#  firebase_core: ^2.22.0

  # localization
  easy_localization: ^3.0.2
  # Routing
  go_router: ^8.0.5

  # DI
  get_it: ^7.6.0
  injectable: ^2.1.2

  # Modeling
  freezed: ^2.3.5
  flutter_polyline_points: ^2.1.0
  firebase_messaging:
  form_builder_validators:
  freezed_annotation: ^2.2.0
#  json_serializable: ^6.7.0
  json_annotation: ^4.8.1

  # State management
  equatable: ^2.0.3
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1
  stream_transform: ^2.1.0
  webview_flutter: ^4.2.2
  provider: ^6.1.2

  #client
  dio: ^5.3.0

  # dev
  dartz: ^0.10.1
  intl: 0.19.0
  tuple: ^2.0.1
  logger: ^1.3.0
  fpdart: ^0.5.0
  faker: ^2.1.0


  #ui
  flutter_screenutil: ^5.7.0
  shared_preferences: ^2.1.0
  flutter_svg: ^1.1.6
  flutter_native_splash: ^2.3.0
  auto_size_text: ^3.0.0
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.2.3
  percent_indicator: ^4.2.3
  carousel_slider: ^4.2.1
  text_scroll: ^0.2.0
  flutter_form_builder: ^9.1.0
#  form_builder_validators: ^9.1.0
  google_maps_flutter: ^2.6.1

  form_field_validator: ^1.1.0
  fancy_shimmer_image: ^2.0.2
  dotted_border: ^2.1.0
  flutter_otp_text_field: ^1.1.1
  animated_size_and_fade:
  cupertino_tabbar:
  page_view_dot_indicator: ^2.3.0
  flutter_rating_bar: ^4.0.1
  easy_animation: ^0.0.2
  pinput: ^3.0.1
  phone_numbers_parser:
  geocoding: ^2.1.1
  geolocator: ^10.0.1
  app_settings: ^5.1.1
  readmore: ^2.2.0
#  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geocoding_platform_interface: ^2.0.1
  location_platform_interface: ^3.1.2
  map_picker: ^0.0.3
  flutter_spinkit: ^5.2.0
#  map_launcher: ^2.5.0+1
  easy_stepper: ^0.8.1
  photo_view: ^0.14.0
  restart_app:
  curved_labeled_navigation_bar: ^2.0.2
  firebase_core: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  bloc_test: ^9.1.1
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
#  share_plus: ^7.2.1
  fluttertoast: ^8.2.4
  carousel_slider: ^4.2.1
flutter:


  uses-material-design: true

  assets:
    - assets/translations/ar.json
    - assets/translations/en.json
    - assets/image/svg/location/
    - assets/image/svg/splash/
    - assets/image/splash.jpg
    - assets/image/svg/send.jpg
    - assets/image/svg/login/background.svg
    - assets/image/svg/signUp/
    - assets/image/svg/verification/
    - assets/svg/category/
    - assets/svg/home/
    - assets/image/svg/details/
    - assets/svg/delete/
    - assets/svg/location/
    - assets/svg/payment/
    - assets/svg/Filtter.svg
    - assets/svg/location_icon.svg
    - assets/svg/home/Group 1045.svg
    - assets/svg/
    - assets/svg/profile/
    - assets/svg/profile/suggest.svg
    - assets/svg/profile/smile.svg
    - assets/svg/language/
    - assets/image/svg/
    - assets/image/
    - assets/image/svg/login/










  fonts:
    - family: Tajawal Regular
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: Tajawal Bold
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/launcher_icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21