// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQnZ6ucLbn2ALJDA7SeFPWjLe5iiQw0OY',
    appId: '1:311035083950:web:7a7324d713ee2eeeeac13f',
    messagingSenderId: '311035083950',
    projectId: 'moll-c41f5',
    authDomain: 'moll-c41f5.firebaseapp.com',
    storageBucket: 'moll-c41f5.appspot.com',
    measurementId: 'G-LE3TVBC0CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsRh9jq4iQs_H2cuK3gicQHoGpVIi_tuA',
    appId: '1:311035083950:android:b6fd3772092a6740eac13f',
    messagingSenderId: '311035083950',
    projectId: 'moll-c41f5',
    storageBucket: 'moll-c41f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG44sXzltgvtE-9Z0EVt-DssRUCDWuRns',
    appId: '1:311035083950:ios:99cade5461e6fa30eac13f',
    messagingSenderId: '311035083950',
    projectId: 'moll-c41f5',
    storageBucket: 'moll-c41f5.appspot.com',
    iosBundleId: 'com.example.remy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG44sXzltgvtE-9Z0EVt-DssRUCDWuRns',
    appId: '1:311035083950:ios:99cade5461e6fa30eac13f',
    messagingSenderId: '311035083950',
    projectId: 'moll-c41f5',
    storageBucket: 'moll-c41f5.appspot.com',
    iosBundleId: 'com.example.remy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQnZ6ucLbn2ALJDA7SeFPWjLe5iiQw0OY',
    appId: '1:311035083950:web:9664f678807fbfcceac13f',
    messagingSenderId: '311035083950',
    projectId: 'moll-c41f5',
    authDomain: 'moll-c41f5.firebaseapp.com',
    storageBucket: 'moll-c41f5.appspot.com',
    measurementId: 'G-QRYR47EFK5',
  );

}